services:
  app:
    restart: unless-stopped
    command: [
      "sh", "-c",
      "uvicorn app.presentation.main:init_api --factory --host ${WEBAPP_WEBHOOK_HOST} --port ${WEBAPP_WEBHOOK_PORT} --no-access-log"
    ]
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; s=socket.create_connection(('127.0.0.1', 8080), 2); s.close()"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: frontend_builder
    volumes:
      - frontend_dist:/dist
    command: sh -c "cp -r /app/dist/* /dist"

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    env_file:
      - ./.env
    depends_on:
      app:
        condition: service_healthy
      certbot:
        condition: service_started
      frontend:
        condition: service_started
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./nginx/start/:/etc/nginx/templates/
      - ./nginx/templates/:/etc/nginx/templates/
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
      - frontend_dist:/var/www/frontend
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/www:/var/www/certbot
    networks:
      - app-network

volumes:
  frontend_dist:

networks:
  app-network:
    driver: bridge
